# -*- coding: utf-8 -*-
"""spam_sms_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xm5qYhAUimMDTwAyKKH2qf_mZIsFM0mq

# Spam SMS Classification using LSTM (RNN)

This project builds a resume-grade Spam SMS classification system using
LSTM-based sequence modeling with TensorFlow/Keras.

Dataset:
- UCI SMS Spam Collection Dataset

Key challenges addressed:
- Short, noisy text sequences
- Severe class imbalance
- Proper evaluation using Precision, Recall, and F1-score
- Industry-aligned NLP pipeline design

IMPORTS & CONFIGURATION
"""

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import pickle

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Reproducibility
tf.random.set_seed(42)
np.random.seed(42)

# CONFIG (LOCKED BY DESIGN)
VOCAB_SIZE = 8000
MAX_LEN = 40
EMBED_DIM = 64
LSTM_UNITS = 64
BATCH_SIZE = 32
EPOCHS = 8

"""LOAD UCI SMS SPAM DATASET"""

import pandas as pd

df = pd.read_csv(
    "/content/spam.csv",
    encoding="latin-1"
)

# Keep only relevant columns
df = df[['v1', 'v2']]

# Rename columns
df.columns = ['label', 'message']

df.head()

df.head()

df.isna().sum()

"""DATA EXPLORATION & IMBALANCE ANALYSIS"""

df.info()

df['label'].value_counts()

"""Observation:
- Dataset is heavily imbalanced
- Accuracy alone will be misleading
- Spam recall must be prioritized

LABEL ENCODING
"""

df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

df['label'].value_counts()

"""TRAIN / TEST SPLIT"""

from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    df['message'].values,
    df['label'].values,
    test_size=0.2,
    stratify=df['label'],
    random_state=42
)

print("Train size:", len(X_train_text))
print("Test size:", len(X_test_text))

"""TOKENIZATION (SMS-AWARE, WORD LEVEL)"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

VOCAB_SIZE = 8000
MAX_LEN = 40

tokenizer = Tokenizer(
    num_words=VOCAB_SIZE,
    oov_token="<OOV>",
    lower=True
)

tokenizer.fit_on_texts(X_train_text)

X_train_seq = tokenizer.texts_to_sequences(X_train_text)
X_test_seq = tokenizer.texts_to_sequences(X_test_text)

"""PADDING & MASKING"""

X_train = pad_sequences(
    X_train_seq,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

X_test = pad_sequences(
    X_test_seq,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

print(X_train.shape, X_test.shape)

HANDLE CLASS IMBALANCE

import numpy as np
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.array([0, 1]),
    y=y_train
)

class_weight_dict = {
    0: class_weights[0],  # ham
    1: class_weights[1]   # spam
}

class_weight_dict

"""LSTM MODEL (MANY-TO-ONE)"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

EMBED_DIM = 64
LSTM_UNITS = 64

model = Sequential([
    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBED_DIM,
        input_length=MAX_LEN,
        mask_zero=True
    ),
    LSTM(
        LSTM_UNITS,
        dropout=0.2,
        recurrent_dropout=0.2
    ),
    Dense(1, activation="sigmoid")
])

model.build(input_shape=(None, MAX_LEN))
model.summary()

"""COMPILE MODEL"""

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]  # accuracy only for monitoring
)

"""TRAIN MODEL"""

EPOCHS = 8
BATCH_SIZE = 32

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    class_weight=class_weight_dict
)

"""PROPER EVALUATION (PRECISION / RECALL / F1)"""

from sklearn.metrics import classification_report, confusion_matrix

y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob >= 0.5).astype(int)

print(classification_report(
    y_test,
    y_pred,
    target_names=["Ham", "Spam"]
))

confusion_matrix(y_test, y_pred)

"""OPTIONAL — THRESHOLD TUNING (ADVANCED, OPTIONAL)"""

# Example: increase spam recall
custom_threshold = 0.35
y_pred_custom = (y_pred_prob >= custom_threshold).astype(int)

print(classification_report(
    y_test,
    y_pred_custom,
    target_names=["Ham", "Spam"]
))

"""SAVE MODEL & TOKENIZER (FOR DEPLOYMENT)"""

model.save("spam_lstm_model.h5")

import pickle

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

"""FINAL MANUAL TEST (LABEL OUTPUT ONLY)"""

def predict_spam_label(text):
    seq = tokenizer.texts_to_sequences([text])
    pad = pad_sequences(seq, maxlen=MAX_LEN, padding="post")
    prob = model.predict(pad, verbose=0)[0][0]
    return "SPAM 🚨" if prob >= 0.5 else "HAM ✅"

predict_spam_label("Congratulations! You have won a free prize. Call now!")

predict_spam_label("I'll reach home by 8pm today")